config:
  baseURL: ""

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressClassName: tailscale
  hosts:
    - host: headlamp
      paths:
        - path: /
          pathType: Prefix
          type: ImplementationSpecific
  tls:
    - secretName: headlamp-tls-cert
      hosts:
        - headlamp
