apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: applications
  labels:
    app: vaultwarden
    annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.33.2-alpine
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          env:
            - name: WEBSOCKET_ENABLED
              value: "true"
            - name: SIGNUPS_ALLOWED
              value: "false"
            - name: DATA_FOLDER
              value: "/data"
          ports:
            - name: http
              containerPort: 80
            - name: websocket
              containerPort: 3012
          volumeMounts:
            - name: vaultwarden-data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: vaultwarden-data
          persistentVolumeClaim:
            claimName: vaultwarden-pvc
        - name: tmp
          emptyDir: {}
