apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: applications
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/part-of: stackcraft
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.33.2-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: WEBSOCKET_ENABLED
              value: "true"
            - name: SIGNUPS_ALLOWED
              value: "true"
          ports:
            - name: http
              containerPort: 80
            - name: websocket
              containerPort: 3012
          volumeMounts:
            - name: vaultwarden-data
              mountPath: /data
      volumes:
        - name: vaultwarden-data
          persistentVolumeClaim:
            claimName: vaultwarden-pvc
