apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: applications
  labels:
    app: vaultwarden
    annotations:
      argocd.argoproj.io/sync-wave: "1"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: websocket
      port: 3012
      targetPort: 3012
      protocol: TCP
  selector:
    app: vaultwarden
