apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  - ingress.yaml
  - rbac.yaml
  - values.yaml

patches:
  - target:
      kind: Ingress
      name: headlamp-ingress
    patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: headlamp-ingress
      spec:
        rules:
          - host: headlamp.chimera-fence.ts.net
        tls:
          - hosts:
              - headlamp.chimera-fence.ts.net
