apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  namespace: applications
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - vault.perch-humboldt.ts.net
      secretName: vault-tls-cert
  rules:
    - host: vault.perch-humboldt.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vaultwarden
                port:
                  name: http
